version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    profiles:
      - local-mongo
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    profiles:
      - local-mongo
volumes:
  mongo_data:
